# Generated by Django 4.0.3 on 2022-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
