# Generated by Django 4.0.3 on 2022-05-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0004_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
