# Generated by Django 4.0.3 on 2022-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0005_alter_usersession_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
