# Generated by Django 4.0.3 on 2022-09-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0007_remove_topic_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-started_at'], 'verbose_name': 'User Session'},
        ),
    ]
