# Generated by Django 4.0.3 on 2022-04-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlalgorithm',
            options={'verbose_name': 'ML Algorithm'},
        ),
        migrations.AlterModelOptions(
            name='mlalgorithmstatus',
            options={'verbose_name': 'ML Algorithm Status', 'verbose_name_plural': 'ML Algorithm Statuses'},
        ),
        migrations.AlterModelOptions(
            name='mlrequest',
            options={'verbose_name': 'ML Request'},
        ),
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='ml_api.mlalgorithm', verbose_name='Parent ML Algorithm'),
        ),
    ]
