# Generated by Django 4.0.3 on 2022-04-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0002_alter_mlalgorithm_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='owner',
        ),
    ]
