# Generated by Django 4.0.3 on 2022-04-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0003_remove_endpoint_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abtest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='created_by',
        ),
    ]
