# Generated by Django 4.0.3 on 2022-05-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0006_usersession_name'),
        ('ml_api', '0005_remove_mlrequest_prediction_mlrequest_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlrequest',
            name='user_session',
            field=models.ForeignKey(default='4d72d91c-d81e-4da6-a39d-bf4efd0f8e8b', on_delete=django.db.models.deletion.CASCADE, to='topics_recommender.usersession'),
            preserve_default=False,
        ),
    ]
