# Generated by Django 4.0.3 on 2022-05-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0006_usersession_name'),
        ('ml_api', '0006_mlrequest_user_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlrequest',
            name='previous_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_api.mlrequest'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='ml_api.mlalgorithm', verbose_name='ranking algorithm'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='user_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='topics_recommender.usersession', verbose_name='user session'),
        ),
    ]
