# Generated by Django 4.0.3 on 2022-05-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0007_mlrequest_previous_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abtest',
            name='algorithm_A',
        ),
        migrations.RemoveField(
            model_name='abtest',
            name='algorithm_B',
        ),
        migrations.AddField(
            model_name='abtest',
            name='algorithms',
            field=models.ManyToManyField(to='ml_api.mlalgorithm'),
        ),
    ]
