# Generated by Django 4.0.3 on 2022-05-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0008_remove_abtest_algorithm_a_remove_abtest_algorithm_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTestingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='ml_api.endpoint', verbose_name='Associated Endpoint')),
            ],
            options={
                'verbose_name': 'Endpoint Status',
                'verbose_name_plural': 'Endpoint Statuses',
            },
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
    ]
