# Generated by Django 4.0.3 on 2022-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0009_mltestingstatus_delete_mlalgorithmstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlalgorithm',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
