# Generated by Django 4.0.3 on 2022-06-01 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0011_alter_mlalgorithm_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='endpoint',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='A/B Test', to='ml_api.endpoint', verbose_name='Associated Endpoint'),
            preserve_default=False,
        ),
    ]
