# Generated by Django 4.0.3 on 2022-06-02 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0012_abtest_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abtest',
            name='algorithms',
        ),
        migrations.RemoveField(
            model_name='abtest',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='ab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_api.abtest', verbose_name='Active A/B Test'),
        ),
    ]
