# Generated by Django 4.0.3 on 2022-06-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0013_remove_abtest_algorithms_remove_abtest_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlrequest',
            options={'get_latest_by': 'created_at', 'verbose_name': 'ML Request'},
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='ab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_api.abtest', verbose_name='Active A/B Test'),
        ),
        migrations.AlterField(
            model_name='mlalgorithm',
            name='parent_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='ml_api.endpoint', verbose_name='Assigned Endpoint'),
        ),
    ]
