# Generated by Django 4.0.3 on 2022-09-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0014_alter_mlrequest_options_alter_endpoint_ab_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithm',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
