# Generated by Django 4.0.3 on 2022-07-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datresponse',
            options={'verbose_name': 'DAT Response'},
        ),
        migrations.AlterModelOptions(
            name='datword',
            options={'verbose_name': 'word'},
        ),
        migrations.AddField(
            model_name='datword',
            name='language_code',
            field=models.CharField(default='en', max_length=2),
            preserve_default=False,
        ),
    ]
