# Generated by Django 4.0.3 on 2022-07-19 11:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_tasks', '0002_alter_datresponse_options_alter_datword_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTTIdea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CTTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CTT Response',
            },
        ),
        migrations.CreateModel(
            name='CTTCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('language_code', models.CharField(max_length=2)),
                ('ideas', models.ManyToManyField(related_name='categories', to='survey_tasks.cttidea')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_titles', to='survey_tasks.cttresponse')),
            ],
        ),
        migrations.CreateModel(
            name='CTTIdeaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey_tasks.cttidea')),
            ],
            options={
                'verbose_name': 'ctt idea Translation',
                'db_table': 'survey_tasks_cttidea_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
