# Generated by Django 4.0.3 on 2022-07-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0007_remove_topic_description_and_more'),
        ('survey_tasks', '0003_cttidea_cttresponse_cttcategory_cttideatranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cttcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='cttidea',
            options={'verbose_name': 'idea'},
        ),
        migrations.AlterModelOptions(
            name='cttideatranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'idea Translation'},
        ),
        migrations.AddField(
            model_name='cttresponse',
            name='user_session',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='topics_recommender.usersession'),
        ),
        migrations.AddField(
            model_name='datresponse',
            name='user_session',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='topics_recommender.usersession'),
        ),
    ]
