# Generated by Django 4.0.3 on 2022-07-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0007_remove_topic_description_and_more'),
        ('survey_tasks', '0004_alter_cttcategory_options_alter_cttidea_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cttresponse',
            name='user_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics_recommender.usersession'),
        ),
        migrations.AlterField(
            model_name='datresponse',
            name='user_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics_recommender.usersession'),
        ),
    ]
