# Generated by Django 4.0.3 on 2022-09-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_tasks', '0006_recommenderresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommenderresponse',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Recommender Task Response'},
        ),
    ]
