# Generated by Django 4.0.3 on 2022-09-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_tasks', '0007_alter_recommenderresponse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datresponse',
            name='dat_score',
            field=models.FloatField(blank=True, null=True, verbose_name='DAT Score'),
        ),
    ]
