# Generated by Django 4.0.3 on 2022-10-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_tasks', '0008_datresponse_dat_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderresponse',
            name='sim_score_1_2',
            field=models.FloatField(null=True, verbose_name='Similarity of Topics 1 & 2'),
        ),
        migrations.AddField(
            model_name='recommenderresponse',
            name='sim_score_2_3',
            field=models.FloatField(null=True, verbose_name='Similarity of Topics 2 & 3'),
        ),
        migrations.AddField(
            model_name='recommenderresponse',
            name='sim_score_3_1',
            field=models.FloatField(null=True, verbose_name='Similarity of Topics 3 & 1'),
        ),
    ]
