# Generated by Django 4.0.3 on 2022-10-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0008_alter_usersession_options'),
        ('survey_tasks', '0009_recommenderresponse_sim_score_1_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenderresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommenderresponse',
            name='topic1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='topics_recommender.topic', verbose_name='Topic 1'),
        ),
        migrations.AlterField(
            model_name='recommenderresponse',
            name='topic2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='topics_recommender.topic', verbose_name='Topic 2'),
        ),
        migrations.AlterField(
            model_name='recommenderresponse',
            name='topic3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='topics_recommender.topic', verbose_name='Topic 3'),
        ),
    ]
