# Generated by Django 4.0.3 on 2022-11-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_recommender', '0008_alter_usersession_options'),
        ('survey_tasks', '0010_recommenderresponse_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderResponseV2',
            fields=[
                ('recommenderresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey_tasks.recommenderresponse')),
                ('sim_score_3_4', models.FloatField(null=True, verbose_name='Similarity of Topics 3 & 4')),
                ('sim_score_4_5', models.FloatField(null=True, verbose_name='Similarity of Topics 4 & 5')),
                ('sim_score_5_1', models.FloatField(null=True, verbose_name='Similarity of Topics 5 & 1')),
                ('sim_score_4_2', models.FloatField(null=True, verbose_name='Similarity of Topics 4 & 2')),
                ('sim_score_4_1', models.FloatField(null=True, verbose_name='Similarity of Topics 4 & 1')),
                ('sim_score_5_2', models.FloatField(null=True, verbose_name='Similarity of Topics 5 & 2')),
                ('sim_score_5_3', models.FloatField(null=True, verbose_name='Similarity of Topics 5 & 3')),
                ('topic4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice4', to='topics_recommender.topic', verbose_name='Topic 4')),
                ('topic5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice5', to='topics_recommender.topic', verbose_name='Topic 5')),
            ],
            options={
                'verbose_name': 'Recommender Task Response V2',
                'ordering': ['-submitted_at'],
            },
            bases=('survey_tasks.recommenderresponse',),
        ),
    ]
